let apps = []

const refreshApps = async () => {
    await new Promise(resolve => {
        setTimeout(resolve, 1000)
    })

    apps = [
        {
            id: 354762,
            name: 'asyncphp.com',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2017-06-22 19:50:55',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/139373/sites/354762/deploy/http?token=JzNsTow7nzSpVIC3N2XtTLmh459gHlseVOz21TOE',
            tags: [],
            server: {
                id: 139373,
                credential_id: 13726,
                name: 'Complex',
                provider: 'ocean2',
                provider_id: '51428033',
                size: '512MB',
                region: 'London',
                php_version: 'php71',
                ip_address: '188.166.150.15',
                ssh_port: 22,
                private_ip_address: '10.131.32.166',
                blackfire_status: 'installed',
                papertrail_status: null,
                revoked: false,
                created_at: '2017-06-11 10:48:32',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'asyncphp.com',
        },
        {
            id: 354784,
            name: 'asynchronousphp.com',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2017-06-22 20:06:54',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/139373/sites/354784/deploy/http?token=FjcPr8doW1XNknrREMztoaapoZXyZBrbqTZ0cnsU',
            tags: [],
            server: {
                id: 139373,
                credential_id: 13726,
                name: 'Complex',
                provider: 'ocean2',
                provider_id: '51428033',
                size: '512MB',
                region: 'London',
                php_version: 'php71',
                ip_address: '188.166.150.15',
                ssh_port: 22,
                private_ip_address: '10.131.32.166',
                blackfire_status: 'installed',
                papertrail_status: null,
                revoked: false,
                created_at: '2017-06-11 10:48:32',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'asynchronousphp.com',
        },
        {
            id: 709625,
            name: 'attempt-promise.assertchris.io',
            aliases: [],
            directory: '/',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'html',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-02-14 23:24:07',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/139373/sites/709625/deploy/http?token=hzNl2tsHy7wphQu0pokjLpImKDeTXvLFWoy7sZ4k',
            tags: [],
            server: {
                id: 139373,
                credential_id: 13726,
                name: 'Complex',
                provider: 'ocean2',
                provider_id: '51428033',
                size: '512MB',
                region: 'London',
                php_version: 'php71',
                ip_address: '188.166.150.15',
                ssh_port: 22,
                private_ip_address: '10.131.32.166',
                blackfire_status: 'installed',
                papertrail_status: null,
                revoked: false,
                created_at: '2017-06-11 10:48:32',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'attempt-promise.assertchris.io',
        },
        {
            id: 780245,
            name: 'new.preprocess.io',
            aliases: ['preprocess.io'],
            directory: '/',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'html',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-06-02 23:40:45',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/139373/sites/780245/deploy/http?token=vffzq6S4vzp6d3CYaQT4EknhUPEZ8jUiSGrpan76',
            tags: [],
            server: {
                id: 139373,
                credential_id: 13726,
                name: 'Complex',
                provider: 'ocean2',
                provider_id: '51428033',
                size: '512MB',
                region: 'London',
                php_version: 'php71',
                ip_address: '188.166.150.15',
                ssh_port: 22,
                private_ip_address: '10.131.32.166',
                blackfire_status: 'installed',
                papertrail_status: null,
                revoked: false,
                created_at: '2017-06-11 10:48:32',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'new.preprocess.io',
        },
        {
            id: 786887,
            name: 'assertchris.io',
            aliases: [],
            directory: '/',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-06-12 20:07:14',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/139373/sites/786887/deploy/http?token=wrYSUScfVIXiRDEJTQog97O7jfPOsOOpF1NwC06Q',
            tags: [],
            server: {
                id: 139373,
                credential_id: 13726,
                name: 'Complex',
                provider: 'ocean2',
                provider_id: '51428033',
                size: '512MB',
                region: 'London',
                php_version: 'php71',
                ip_address: '188.166.150.15',
                ssh_port: 22,
                private_ip_address: '10.131.32.166',
                blackfire_status: 'installed',
                papertrail_status: null,
                revoked: false,
                created_at: '2017-06-11 10:48:32',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'assertchris.io',
        },
        {
            id: 790994,
            name: 'notes.assertchris.io',
            aliases: [],
            directory: '/',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'html',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-06-19 00:04:02',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/139373/sites/790994/deploy/http?token=11VKHARULcj3loN6n1VvMAOHCSGuIWDCxQi5gQY6',
            tags: [],
            server: {
                id: 139373,
                credential_id: 13726,
                name: 'Complex',
                provider: 'ocean2',
                provider_id: '51428033',
                size: '512MB',
                region: 'London',
                php_version: 'php71',
                ip_address: '188.166.150.15',
                ssh_port: 22,
                private_ip_address: '10.131.32.166',
                blackfire_status: 'installed',
                papertrail_status: null,
                revoked: false,
                created_at: '2017-06-11 10:48:32',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'notes.assertchris.io',
        },
        {
            id: 793702,
            name: 'scriptures.assertchris.io',
            aliases: [],
            directory: '/',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'html',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-06-23 13:01:43',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/139373/sites/793702/deploy/http?token=yqaeW9GKuq16TskWGwtB4dxxyxzqesa6ug2I0uGg',
            tags: [],
            server: {
                id: 139373,
                credential_id: 13726,
                name: 'Complex',
                provider: 'ocean2',
                provider_id: '51428033',
                size: '512MB',
                region: 'London',
                php_version: 'php71',
                ip_address: '188.166.150.15',
                ssh_port: 22,
                private_ip_address: '10.131.32.166',
                blackfire_status: 'installed',
                papertrail_status: null,
                revoked: false,
                created_at: '2017-06-11 10:48:32',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'scriptures.assertchris.io',
        },
        {
            id: 360832,
            name: 'clayjarpeople.co.za',
            aliases: null,
            directory: '',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: 'WordPress',
            app_status: 'installed',
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2017-07-03 19:05:25',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/142621/sites/360832/deploy/http?token=kvcSbQFZwGOF6G1MgfeNlOWzcAZNtk7k2uhFWVJC',
            tags: [],
            server: {
                id: 142621,
                credential_id: 13726,
                name: 'Simple',
                provider: 'ocean2',
                provider_id: '53852837',
                size: '512MB',
                region: 'Amsterdam 2',
                php_version: 'php71',
                ip_address: '95.85.29.7',
                ssh_port: 22,
                private_ip_address: '10.129.28.230',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2017-07-03 18:47:09',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'clayjarpeople.co.za',
        },
        {
            id: 361105,
            name: 'rebuildinglaravel.com',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2017-07-04 10:02:16',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/142621/sites/361105/deploy/http?token=bbRUrELAT9CXD55f7FaTOj045oSzM9olPKzo2aYF',
            tags: [],
            server: {
                id: 142621,
                credential_id: 13726,
                name: 'Simple',
                provider: 'ocean2',
                provider_id: '53852837',
                size: '512MB',
                region: 'Amsterdam 2',
                php_version: 'php71',
                ip_address: '95.85.29.7',
                ssh_port: 22,
                private_ip_address: '10.129.28.230',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2017-07-03 18:47:09',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'rebuildinglaravel.com',
        },
        {
            id: 361108,
            name: 'undemanding.io',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2017-07-04 10:03:57',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/142621/sites/361108/deploy/http?token=awCHx5Pk2hwvyLTQvVci0mufvmigadrtZs2xKB52',
            tags: [],
            server: {
                id: 142621,
                credential_id: 13726,
                name: 'Simple',
                provider: 'ocean2',
                provider_id: '53852837',
                size: '512MB',
                region: 'Amsterdam 2',
                php_version: 'php71',
                ip_address: '95.85.29.7',
                ssh_port: 22,
                private_ip_address: '10.129.28.230',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2017-07-03 18:47:09',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'undemanding.io',
        },
        {
            id: 361109,
            name: 'minecraftlang.org',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2017-07-04 10:04:04',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/142621/sites/361109/deploy/http?token=ZCOhyTGUu1J9DhLRZswR0U4cPastWz3RvHMz4J2K',
            tags: [],
            server: {
                id: 142621,
                credential_id: 13726,
                name: 'Simple',
                provider: 'ocean2',
                provider_id: '53852837',
                size: '512MB',
                region: 'Amsterdam 2',
                php_version: 'php71',
                ip_address: '95.85.29.7',
                ssh_port: 22,
                private_ip_address: '10.129.28.230',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2017-07-03 18:47:09',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'minecraftlang.org',
        },
        {
            id: 459799,
            name: 'wayneandsim.club',
            aliases: null,
            directory: '/',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/wayneandsim.club',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: true,
            deployment_status: null,
            project_type: 'html',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2018-01-07 16:50:22',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/142621/sites/459799/deploy/http?token=IWECC5V4Gf3bjoHdN8G5sZqNCI73jd8L345C17mD',
            tags: [],
            server: {
                id: 142621,
                credential_id: 13726,
                name: 'Simple',
                provider: 'ocean2',
                provider_id: '53852837',
                size: '512MB',
                region: 'Amsterdam 2',
                php_version: 'php71',
                ip_address: '95.85.29.7',
                ssh_port: 22,
                private_ip_address: '10.129.28.230',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2017-07-03 18:47:09',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'wayneandsim.club',
        },
        {
            id: 600223,
            name: 'thumbnails.assertchris.io',
            aliases: null,
            directory: '/',
            wildcards: false,
            status: 'installed',
            repository: 'atfotc/thumbnails',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'html',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2018-08-21 14:56:13',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/142621/sites/600223/deploy/http?token=2Tl1Ovsf9Mp6463VwLtu34yx79JPZZEAZRkYQoOp',
            tags: [],
            server: {
                id: 142621,
                credential_id: 13726,
                name: 'Simple',
                provider: 'ocean2',
                provider_id: '53852837',
                size: '512MB',
                region: 'Amsterdam 2',
                php_version: 'php71',
                ip_address: '95.85.29.7',
                ssh_port: 22,
                private_ip_address: '10.129.28.230',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2017-07-03 18:47:09',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'thumbnails.assertchris.io',
        },
        {
            id: 680942,
            name: 'knotnormal.store',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2018-12-31 21:36:25',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/142621/sites/680942/deploy/http?token=h9BogyIrYUC8PIkZZI8mfTFqSxrZO6fNfeDxM0Ng',
            tags: [],
            server: {
                id: 142621,
                credential_id: 13726,
                name: 'Simple',
                provider: 'ocean2',
                provider_id: '53852837',
                size: '512MB',
                region: 'Amsterdam 2',
                php_version: 'php71',
                ip_address: '95.85.29.7',
                ssh_port: 22,
                private_ip_address: '10.129.28.230',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2017-07-03 18:47:09',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'knotnormal.store',
        },
        {
            id: 760578,
            name: 'orangeskiphire.co.za',
            aliases: ['www.orangeskiphire.co.za'],
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: 'WordPress',
            app_status: 'installed',
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-05-05 11:39:30',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/142621/sites/760578/deploy/http?token=6g3lUQHuOANtMDhkeHLtvX6cy5rAheXKSHoIAQ02',
            tags: [],
            server: {
                id: 142621,
                credential_id: 13726,
                name: 'Simple',
                provider: 'ocean2',
                provider_id: '53852837',
                size: '512MB',
                region: 'Amsterdam 2',
                php_version: 'php71',
                ip_address: '95.85.29.7',
                ssh_port: 22,
                private_ip_address: '10.129.28.230',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2017-07-03 18:47:09',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'orangeskiphire.co.za',
        },
        {
            id: 577212,
            name: 'beta.gitstore.app',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/gitstore',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2018-07-16 00:41:19',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/201872/sites/577212/deploy/http?token=MMdnFDtebxWONvhXIlGq133k02HphbRLIvL5o5cx',
            tags: [],
            server: {
                id: 201872,
                credential_id: 41984,
                name: 'gitstore',
                provider: 'vultr',
                provider_id: '15554667',
                size: '2GB',
                region: 'New Jersey',
                php_version: 'php72',
                ip_address: '8.9.4.10',
                ssh_port: 22,
                private_ip_address: '10.1.96.3',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2018-05-11 02:04:47',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'beta.gitstore.app',
        },
        {
            id: 647976,
            name: 'enjoy.gitstore.app',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/gitstore',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2018-11-07 00:09:22',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/226120/sites/647976/deploy/http?token=wuYZW0ljAKZcvbazxQNAYWRGinLE5LwwsJ7bxyCm',
            tags: [],
            server: {
                id: 226120,
                credential_id: 41984,
                name: 'gitstore-prod',
                provider: 'vultr',
                provider_id: '18201585',
                size: '4GB',
                region: 'Amsterdam',
                php_version: 'php72',
                ip_address: '209.250.253.216',
                ssh_port: 22,
                private_ip_address: '10.7.96.3',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2018-08-24 14:53:09',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'enjoy.gitstore.app',
        },
        {
            id: 89537,
            name: 'rebuildinglaravel.com',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/rebuildinglaravel.com',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2015-08-21 15:53:56',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/42653/sites/89537/deploy/http?token=NKLNloMYFvEfjOanPpGHILEYehqGkDblki8B4ais',
            tags: [],
            server: {
                id: 42653,
                credential_id: 13726,
                name: 'hacked-to-shit',
                provider: 'ocean',
                provider_id: '6745739',
                size: '1GB',
                region: 'London',
                php_version: 'php56-old',
                ip_address: '46.101.6.189',
                ssh_port: 22,
                private_ip_address: '10.131.13.233',
                blackfire_status: null,
                papertrail_status: null,
                revoked: true,
                created_at: '2015-08-21 15:47:02',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'rebuildinglaravel.com',
        },
        {
            id: 89538,
            name: 'rebuildingmootools.com',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/rebuildingmootools.com',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2015-08-21 15:54:03',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/42653/sites/89538/deploy/http?token=tYAdqUppEIWSHZEo1Wuc5UocAMMSCfHqcrEtb4rX',
            tags: [],
            server: {
                id: 42653,
                credential_id: 13726,
                name: 'hacked-to-shit',
                provider: 'ocean',
                provider_id: '6745739',
                size: '1GB',
                region: 'London',
                php_version: 'php56-old',
                ip_address: '46.101.6.189',
                ssh_port: 22,
                private_ip_address: '10.131.13.233',
                blackfire_status: null,
                papertrail_status: null,
                revoked: true,
                created_at: '2015-08-21 15:47:02',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'rebuildingmootools.com',
        },
        {
            id: 89539,
            name: 'tonypitt.co.za',
            aliases: null,
            directory: '',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/tonypitt.co.za',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2015-08-21 15:54:15',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/42653/sites/89539/deploy/http?token=rn2bvRASW1GI1wRC9H7RR4sMaV7qkYtwRWegVniL',
            tags: [],
            server: {
                id: 42653,
                credential_id: 13726,
                name: 'hacked-to-shit',
                provider: 'ocean',
                provider_id: '6745739',
                size: '1GB',
                region: 'London',
                php_version: 'php56-old',
                ip_address: '46.101.6.189',
                ssh_port: 22,
                private_ip_address: '10.131.13.233',
                blackfire_status: null,
                papertrail_status: null,
                revoked: true,
                created_at: '2015-08-21 15:47:02',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'tonypitt.co.za',
        },
        {
            id: 89540,
            name: 'clayjarpeople.co.za',
            aliases: null,
            directory: '',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2015-08-21 15:54:23',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/42653/sites/89540/deploy/http?token=jShIlTpheVUn0QsKosgmul56s95wQOETTTmGl45d',
            tags: [],
            server: {
                id: 42653,
                credential_id: 13726,
                name: 'hacked-to-shit',
                provider: 'ocean',
                provider_id: '6745739',
                size: '1GB',
                region: 'London',
                php_version: 'php56-old',
                ip_address: '46.101.6.189',
                ssh_port: 22,
                private_ip_address: '10.131.13.233',
                blackfire_status: null,
                papertrail_status: null,
                revoked: true,
                created_at: '2015-08-21 15:47:02',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'clayjarpeople.co.za',
        },
        {
            id: 361106,
            name: 'minecraftlang.org',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2017-07-04 10:03:33',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/42653/sites/361106/deploy/http?token=WhLv4pwT9U5XlASl7uXuAs5qcPECIXVhAh11rLLi',
            tags: [],
            server: {
                id: 42653,
                credential_id: 13726,
                name: 'hacked-to-shit',
                provider: 'ocean',
                provider_id: '6745739',
                size: '1GB',
                region: 'London',
                php_version: 'php56-old',
                ip_address: '46.101.6.189',
                ssh_port: 22,
                private_ip_address: '10.131.13.233',
                blackfire_status: null,
                papertrail_status: null,
                revoked: true,
                created_at: '2015-08-21 15:47:02',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'minecraftlang.org',
        },
        {
            id: 361107,
            name: 'undemanding.io',
            aliases: null,
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2017-07-04 10:03:46',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/42653/sites/361107/deploy/http?token=LoOorTftNooqRMOz7Hd3kpZXyLTErAH2OGBOBHfU',
            tags: [],
            server: {
                id: 42653,
                credential_id: 13726,
                name: 'hacked-to-shit',
                provider: 'ocean',
                provider_id: '6745739',
                size: '1GB',
                region: 'London',
                php_version: 'php56-old',
                ip_address: '46.101.6.189',
                ssh_port: 22,
                private_ip_address: '10.131.13.233',
                blackfire_status: null,
                papertrail_status: null,
                revoked: true,
                created_at: '2015-08-21 15:47:02',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'undemanding.io',
        },
        {
            id: 884119,
            name: 'gitstore-components.assertchris.io',
            aliases: [],
            directory: '/demo/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/gitstore-components',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-11-06 14:00:16',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/884119/deploy/http?token=A34e0qCQlGrK3Sxl9sPGOr8RgJ9hrbmJ4OtXoHz0',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'gitstore-components.assertchris.io',
        },
        {
            id: 884148,
            name: 'silverstripe-demo.assertchris.io',
            aliases: [],
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: null,
            repository_provider: null,
            repository_branch: null,
            repository_status: null,
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-11-06 14:41:26',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/884148/deploy/http?token=9pvMMWZSA3IUQJ1ER1GxnAubtFZEdegqVV4Eau6U',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'silverstripe-demo.assertchris.io',
        },
        {
            id: 903454,
            name: 'grow.assertchris.io',
            aliases: [],
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/grow',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-12-05 01:27:18',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/903454/deploy/http?token=GUIu6r9ueTyNGBGhr4K3UvYG8W2H4g0ud1IR8mmH',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'grow.assertchris.io',
        },
        {
            id: 911436,
            name: 'assertchris.io',
            aliases: ['new.assertchris.io'],
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/assertchris.io',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-12-17 02:11:43',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/911436/deploy/http?token=3fPMMtQxp4Qzgi5oiqgAHH0NbvhkYMJpB1iQgBWA',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'assertchris.io',
        },
        {
            id: 941907,
            name: 'gitstore-two.assertchris.io',
            aliases: [],
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/gitstore-app-two',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: true,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2020-01-21 23:18:12',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/941907/deploy/http?token=S2IEn9pg88V7NQHf29bcC4CexPIkxAXnNAx9oZfG',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'gitstore-two.assertchris.io',
        },
        {
            id: 945136,
            name: 'roasting-app.assertchris.io',
            aliases: [],
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/roasting-app',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: true,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2020-01-26 18:04:45',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/945136/deploy/http?token=p8iQHlQ4weEdvtD3HLiJPcLhLaMhEQbrGbQfNLM4',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'roasting-app.assertchris.io',
        },
        {
            id: 948497,
            name: 'use-noto.assertchris.io',
            aliases: [],
            directory: '/',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/use-noto-web',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: true,
            deployment_status: null,
            project_type: 'html',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2020-01-31 00:01:11',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/948497/deploy/http?token=NZJBiUQc9h66mQUW5ldRbqUHhBq0foXTjawPFeQN',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'use-noto.assertchris.io',
        },
        {
            id: 984247,
            name: 'measure.assertchris.io',
            aliases: [],
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/measure',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: true,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2020-03-15 10:47:17',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/984247/deploy/http?token=K7zaikAjhpfkjUt3RwmzVqCcNzD52X86w4PHDY9h',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'measure.assertchris.io',
        },
        {
            id: 1009379,
            name: 'tehillah.assertchris.io',
            aliases: [],
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'atfotc/tehillah-admin',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2020-04-11 12:51:12',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/1009379/deploy/http?token=lefmOO7ae97C9IExXY0SyycqN0Be8HyYkfoT7NFY',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'tehillah.assertchris.io',
        },
        {
            id: 1009549,
            name: 'tehillah-embed.assertchris.io',
            aliases: [],
            directory: '/',
            wildcards: false,
            status: 'installed',
            repository: 'atfotc/tehillah-embed',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'html',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2020-04-11 18:24:27',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/1009549/deploy/http?token=Gq5Y13VisAVv3E5VKFAIPpGFmViWe7j8CGdjdlEE',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'tehillah-embed.assertchris.io',
        },
        {
            id: 1017433,
            name: 'pixelated.computer',
            aliases: [],
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/pixelated-computer-website',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2020-04-21 06:45:46',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/328382/sites/1017433/deploy/http?token=dT7kHKPtFN8zOmItIvA4cLyoBjUQinEqdpYFKZeB',
            tags: [],
            server: {
                id: 328382,
                credential_id: 13726,
                name: 'simple',
                provider: 'ocean2',
                provider_id: '165792148',
                size: '01',
                region: 'Amsterdam 3',
                php_version: 'php74',
                ip_address: '134.209.205.189',
                ssh_port: 22,
                private_ip_address: '10.133.80.81',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-11-06 13:47:14',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'pixelated.computer',
        },
        {
            id: 875169,
            name: 'validose.assertchris.io',
            aliases: [],
            directory: '/public',
            wildcards: false,
            status: 'installed',
            repository: 'assertchris/validose-server',
            repository_provider: 'github',
            repository_branch: 'master',
            repository_status: 'installed',
            quick_deploy: false,
            deployment_status: null,
            project_type: 'php',
            app: null,
            app_status: null,
            slack_channel: null,
            telegram_chat_id: null,
            telegram_chat_title: null,
            created_at: '2019-10-23 23:50:50',
            username: 'forge',
            deployment_url:
                'https://forge.laravel.com/servers/325295/sites/875169/deploy/http?token=WlkfEky0i8D9Hia4gQf82yT6rMXbtpqjsMnaPhtK',
            tags: [],
            server: {
                id: 325295,
                credential_id: 13726,
                name: 'validose',
                provider: 'ocean2',
                provider_id: '164103146',
                size: '01',
                region: 'San Francisco 2',
                php_version: 'php73',
                ip_address: '167.71.150.106',
                ssh_port: 22,
                private_ip_address: '10.138.192.87',
                blackfire_status: null,
                papertrail_status: null,
                revoked: false,
                created_at: '2019-10-23 23:36:34',
                is_ready: true,
                tags: [],
                network: [],
            },
            short_name: 'validose.assertchris.io',
        },
    ]

    return apps
}

export { refreshApps }
